# Generated by Django 6.0.1 on 2026-01-19 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('last_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('RE', 'Reading'), ('FI', 'Finished')], max_length=2)),
                ('published_date', models.DateField()),
                ('read_date', models.DateField(blank=True, null=True)),
                ('cover_image', models.FileField(blank=True, upload_to='covers/')),
                ('authors', models.ManyToManyField(blank=True, to='bookapp.author')),
            ],
        ),
    ]
